{% set name = "ci-sdr" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ci_sdr-{{ version }}.tar.gz
  sha256: 3f9d4c205b9b7c5c3239a90400b81f1f26ecb38484a46150d2677ff646a13465

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - einops
    - numpy
    - python >={{ python_min }}
    - scipy
    - pytorch

test:
  imports:
    - ci_sdr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fgnt/ci_sdr
  summary: An implementation for the Convolutive transfer function Invariant Signal-to-Distortion Ratio objective for PyTorch
  description: |
    An implementation for the Convolutive transfer function Invariant Signal-to-Distortion Ratio objective for PyTorch as described in the publication Convolutive Transfer Function Invariant SDR training criteria for Multi-Channel Reverberant Speech Separation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wietsedv
